name:                thetundra
version:             0.1.1
github:              "xavier2910/thetundra"
license:             GPL-3
author:              "Xavier Distelzweig"
maintainer:          "x.distelzweig@gmail.com"
copyright:           "none"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
synopsis:            sequel to The Cave and The Forest
category:            Desktop/Text Adventure

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/xavier2910/thetundra#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- mtl >= 2.2.2

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  thetundra:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - thetundra

tests:
  thetundra-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - thetundra
