name: "Fourmat"

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  format:
    name: Format with Fourmolu
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v3
        
      - name: Run Fourmolu
        uses: haskell-actions/run-fourmolu@v9
            
